# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9e48bc3938e4b862ffb1596d1d264d7b7d43f15e518e2e0000bb1f04e62200f90a4250b61ac84486f0f993ab9698570343232e514a265e7084b73a75d7cdcdae

test:
  secret_key_base: 1e92252d989e038f744f988ea94dc579a6bb3ddef54bddf13cfb371f5530f29d3cbaa5b8522e0ff5c3285a3796f531fe0871a59c4a318bcf0de4635f503db681

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
