# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9d8a6af046c53d88f86c8a78dc7651a761c89646d20dcc86e0966a3a18570ab989e51dce9a1157847561523539831e13e47d832c195a01afeb02bf5b6f8fc3f6

test:
  secret_key_base: 832b9daa26134e3f0314461415ef14ef451793860f8b38f2401d197e99eeb60eff023b4b29f0693907005b89b24b947227107ac1658cde8a899e8d61927d1142

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
